import 'package:flutter/material.dart';

/// Maps every icon slug in `constellation_shapes_v2.dart` to Flutter's
/// built-in [Icons] constant of the same name — verified against the
/// Flutter SDK's Icons class, so every current slug has an exact match.
/// [iconForSlug] falls back to a generic star for any slug added later
/// that doesn't (Flutter's classic Icons set doesn't cover every newer
/// Material Symbols name).
const Map<String, IconData> _iconsBySlug = {
  'account_balance': Icons.account_balance,
  'account_balance_wallet': Icons.account_balance_wallet,
  'air': Icons.air,
  'all_inclusive': Icons.all_inclusive,
  'badge': Icons.badge,
  'bolt': Icons.bolt,
  'brightness_4': Icons.brightness_4,
  'brightness_5': Icons.brightness_5,
  'business_center': Icons.business_center,
  'campaign': Icons.campaign,
  'checklist': Icons.checklist,
  'church': Icons.church,
  'connect_without_contact': Icons.connect_without_contact,
  'corporate_fare': Icons.corporate_fare,
  'credit_score': Icons.credit_score,
  'diversity_3': Icons.diversity_3,
  'eco': Icons.eco,
  'emoji_objects': Icons.emoji_objects,
  'engineering': Icons.engineering,
  'explore': Icons.explore,
  'family_restroom': Icons.family_restroom,
  'favorite': Icons.favorite,
  'fitness_center': Icons.fitness_center,
  'flag': Icons.flag,
  'forum': Icons.forum,
  'group_add': Icons.group_add,
  'groups': Icons.groups,
  'groups_2': Icons.groups_2,
  'healing': Icons.healing,
  'laptop_mac': Icons.laptop_mac,
  'local_florist': Icons.local_florist,
  'military_tech': Icons.military_tech,
  'monitor_heart': Icons.monitor_heart,
  'mood': Icons.mood,
  'mosque': Icons.mosque,
  'nightlight': Icons.nightlight,
  'paid': Icons.paid,
  'park': Icons.park,
  'payments': Icons.payments,
  'pie_chart': Icons.pie_chart,
  'pool': Icons.pool,
  'psychology': Icons.psychology,
  'psychology_alt': Icons.psychology_alt,
  'real_estate_agent': Icons.real_estate_agent,
  'recycling': Icons.recycling,
  'redeem': Icons.redeem,
  'request_quote': Icons.request_quote,
  'rocket_launch': Icons.rocket_launch,
  'savings': Icons.savings,
  'school': Icons.school,
  'spa': Icons.spa,
  'sports_gymnastics': Icons.sports_gymnastics,
  'star': Icons.star,
  'synagogue': Icons.synagogue,
  'temple_buddhist': Icons.temple_buddhist,
  'trending_up': Icons.trending_up,
  'volunteer_activism': Icons.volunteer_activism,
  'work': Icons.work,
  'work_history': Icons.work_history,
};

IconData iconForSlug(String slug) => _iconsBySlug[slug] ?? Icons.star_border;
